server:
  port: 8081
  context-path: /springboot
  jsp-servlet:
    init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.baizhi.entity
